import Head from "next/head";
import React from "react";
import Navbar from "../comonents/Navbar";
import Footer from "../comonents/Footer";

const layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Navbar />
      {children}
      <Footer />
    </div>
  );
};

export default layout;
